Repository apache/hbase, pull requests merged in 2019-12, with the labels that each got.

#947 HBASE-20461 Implement fsync for AsyncFSWAL
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncFSWAL.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AsyncProtobufLogWriter.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/CombinedAsyncWriter.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALProvider.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWALDurability.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestFSHLogDurability.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/WALDurabilityTestBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/WriterOverAsyncWriter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/DualAsyncFSWALForTest.java
Labels: feature

#953 HBASE-23594 Procedure stuck due to region happen to recorded on two s…
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRaceBetweenSCPAndTRSP.java
Labels: bug

#964 HBASE-23619 Used built-in formatting for logger in hbase-zookeeper
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/DeletionListener.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/LoadBalancerTracker.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MetaTableLocator.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/MiniZooKeeperCluster.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/RecoverableZooKeeper.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKAclReset.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKLeaderManager.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKNodeTracker.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKUtil.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
Labels: enhancement

#968 HBASE-23622 Reduced the number of Checkstyle violations in hbase-common
  hbase-common/src/main/java/org/apache/hadoop/hbase/BBKVComparator.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/CellComparator.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/CellComparatorImpl.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/net/Address.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/trace/SpanReceiverHost.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/trace/TraceUtil.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteRangeUtils.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/CommonFSUtils.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/ConcatenatedLists.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/Order.java
Labels: enhancement

#972 HBASE-23626 Reduced number of Checkstyle violations in tests in hbase-common
  hbase-common/src/test/java/org/apache/hadoop/hbase/net/TestAddress.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/types/TestStruct.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/types/TestUnion2.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/ClassLoaderTestHelper.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/EnvironmentEdgeManagerTestHelper.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestBytes.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestCoprocessorClassLoader.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestOrderedBytes.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestSimplePositionedMutableByteRange.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/TimeOffsetEnvironmentEdge.java
Labels: enhancement
