Repository apache/hbase, pull requests merged in 2020-03, with the labels that each got.

#1235 HBASE-23921 Findbugs is OOM on master
  dev-support/hbase-personality.sh
Labels: enhancement

#1223 HBASE-23739 BoundedRecoveredHFilesOutputSink should read the table de…
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitLogWorker.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedRecoveredHFilesOutputSink.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestWALReplay.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALReaderOnSecureWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplit.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplitToHFile.java
Labels: bug

#1221 HBASE-23895 STUCK Region-In-Transition when failed to insert procedur…
  hbase-server/src/main/java/org/apache/hadoop/hbase/ipc/RpcServer.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/procedure2/store/region/RegionProcedureStore.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/procedure2/store/region/TestRegionProcedureStore.java
Labels: bug

#1265 HBASE-23077 move entirely to spotbugs
  dev-support/docker/Dockerfile
  dev-support/hbase-personality.sh
  dev-support/jenkins_precommit_github_yetus.sh
  dev-support/spotbugs-exclude.xml
  hbase-archetypes/pom.xml
  hbase-client/pom.xml
  hbase-common/pom.xml
  hbase-examples/pom.xml
  hbase-hbtop/pom.xml
  hbase-http/pom.xml
  hbase-mapreduce/pom.xml
  hbase-procedure/pom.xml
  hbase-protocol-shaded/pom.xml
  hbase-rest/pom.xml
  hbase-server/pom.xml
  hbase-shaded/hbase-shaded-check-invariants/pom.xml
  hbase-shaded/hbase-shaded-client-byo-hadoop/pom.xml
  hbase-shaded/hbase-shaded-client/pom.xml
  hbase-shaded/hbase-shaded-testing-util/pom.xml
  hbase-shaded/hbase-shaded-with-hadoop-check-invariants/pom.xml
  hbase-shaded/pom.xml
  hbase-shell/pom.xml
  hbase-thrift/pom.xml
  hbase-zookeeper/pom.xml
  pom.xml
Labels: enhancement

#1220 HBASE-23847 Removed deprecated setStartRow from Scan
  hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/MetaTableAccessor.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestScan.java
  hbase-endpoint/src/main/java/org/apache/hadoop/hbase/client/coprocessor/AggregationClient.java
  hbase-endpoint/src/main/java/org/apache/hadoop/hbase/coprocessor/Export.java
  hbase-it/src/test/java/org/apache/hadoop/hbase/test/IntegrationTestBigLinkedList.java
  hbase-it/src/test/java/org/apache/hadoop/hbase/trace/IntegrationTestSendTraceRequests.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/ExportUtils.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HashTable.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/MultiTableInputFormat.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/MultiTableInputFormatBase.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/RowCounter.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/SyncTable.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableInputFormat.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableInputFormatBase.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/replication/VerifyReplication.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/MultiTableInputFormatTestBase.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableInputFormat.java
  hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/TableResource.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide5.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFilter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFilterListOrOperatorWithBlkCnt.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSeekOptimizations.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestTags.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestCellACLs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestWithDisabledAuthorization.java
  hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/ThriftHBaseServiceHandler.java
  hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftUtilities.java
Labels: enhancement

#1253 HBASE-23943 Updated Rubocop configuration to current version
  .rubocop.yml
Labels: enhancement

#1307 HBASE-23943 Updated Rubocop configuration to current version
  .rubocop.yml
Labels: backport

#1308 HBASE-23943 Updated Rubocop configuration to current version
  .rubocop.yml
Labels: backport

#1208 HBASE-23845 Removed deprecated setMaxVersions from Scan
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestImportExport.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTimeRangeMapRed.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/TestPartialResultsFromClientSide.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide5.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestScannersFromClientSide.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestTimestampsFilter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestColumnPrefixFilter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestColumnRangeFilter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestFilterListOrOperatorWithBlkCnt.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestMultipleColumnPrefixFilter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestColumnSeeking.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestKeepDeletes.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestNewVersionBehaviorFromClientSide.java
Labels: enhancement

#1213 HBASE-23846 Removed deprecated setMaxVersions(int) from Scan
  hbase-backup/src/main/java/org/apache/hadoop/hbase/backup/impl/BackupSystemTable.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
  hbase-it/src/test/java/org/apache/hadoop/hbase/mapreduce/IntegrationTestBulkLoad.java
  hbase-it/src/test/java/org/apache/hadoop/hbase/mttr/IntegrationTestMTTR.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/CellCounter.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/ExportUtils.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/HashTable.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableInputFormat.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/replication/VerifyReplication.java
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mob/mapreduce/MobRefReporter.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/ScanPerformanceEvaluation.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTimeRangeMapRed.java
  hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/ScannerResultGenerator.java
  hbase-rest/src/main/java/org/apache/hadoop/hbase/rest/TableResource.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/TestSerialization.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/FromClientSideBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide4.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide5.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestMultipleTimestamps.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestOpenTableInCoprocessor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/filter/TestDependentColumnFilter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestDefaultMobStoreFlusher.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobDataBlockEncoding.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobStoreScanner.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBlocksScanned.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestHRegion.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestKeepDeletes.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScannerWithBulkload.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSeekOptimizations.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestWideScanner.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/security/visibility/TestVisibilityLabels.java
  hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/ThriftUtilities.java
  hbase-thrift/src/test/java/org/apache/hadoop/hbase/thrift2/TestThriftConnection.java
Labels: enhancement
