Repository apache/hbase, pull requests merged in 2020-06, with the labels that each got.

#1789 HBASE-22738 Fallback to default group to choose RS when there are no …
  hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsFallback.java
Labels: feature

#1842 HBASE-24501 Backport to branch-1 HBASE-15785 Unnecessary lock in Byte…
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferArray.java
Labels: backport

#1840 HBASE-24500 The behavior of RegionInfoBuilder.newBuilder(RegionInfo) …
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionInfoBuilder.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionReplicaUtil.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionInfoBuilder.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/shaded/protobuf/TestProtobufUtil.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestReadAndWriteRegionInfoFile.java
Labels: bug

#1722 HBASE-24359 Optionally ignore edits for deleted CFs for replication
  hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationDroppedTables.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEditsDroppedWithDeletedTableCFs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEditsDroppedWithDroppedTable.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStuckWithDeletedTableCFs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStuckWithDroppedTable.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestHBaseInterClusterReplicationEndpointFilterEdits.java
Labels: feature

#1823 HBASE-24485 Backport to branch-1 HBASE-17738 BucketCache startup is slow
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferAllocator.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/ByteBufferArray.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/util/TestByteBufferArray.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/bucket/ByteBufferIOEngine.java
Labels: backport

#1851 HBASE-24504 refactor call setupCluster/tearDownCluster in TestTableSnapshotInputFormat
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapred/TestTableSnapshotInputFormat.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TableSnapshotInputFormatTestBase.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/mapreduce/TestTableSnapshotInputFormat.java
Labels: enhancement

#1850 HBASE-24500 The behavior of RegionInfoBuilder.newBuilder(RegionInfo) …
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionInfoBuilder.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/RegionReplicaUtil.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestRegionInfoBuilder.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestReadAndWriteRegionInfoFile.java
Labels: bug

#1863 HBASE-24513 The default readRpcTimeout and writeRpcTimeout is incorre…
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionConfiguration.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncConnectionConfiguration.java
Labels: bug

#1858 HBASE-24506 async client deadlock
  hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/IPCUtil.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcConnection.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/ipc/TestIPCUtil.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyRpcConnection.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableGetMultiThreaded.java
Labels: bug

#1855 HBASE-24359 Optionally ignore edits for deleted CFs for replication
  hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/WALUtil.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationDroppedTables.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEditsDroppedWithDeletedTableCFs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEditsDroppedWithDroppedTable.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStuckWithDeletedTableCFs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStuckWithDroppedTable.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestHBaseInterClusterReplicationEndpointFilterEdits.java
Labels: backport

#1866 HBASE-24517 AssignmentManager.start should add meta region to ServerS…
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestAssignmentManagerLoadMetaRegionState.java
Labels: bug

#1802 HBASE-24444 Should shutdown mini cluster after class in TestMetaAssignmentWithStopMaster
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMetaAssignmentWithStopMaster.java
Labels: enhancement

#1865 HBASE-24117 Shutdown AssignmentManager before ProcedureExecutor may c…
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestCloseRegionWhileRSCrash.java
Labels: bug

#1875 Backport: HBASE-23202 ExportSnapshot (import) will fail if copying files to roo…
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotFileCache.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotHFileCleaner.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotDescriptionUtils.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotFileCache.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotFileCacheWithDifferentWorkingDir.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotHFileCleaner.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/SnapshotTestingUtils.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestSnapshotDescriptionUtils.java
Labels: backport

#1876 backport: HBASE-23202 ExportSnapshot (import) will fail if copying files to roo…
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotFileCache.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/SnapshotHFileCleaner.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/snapshot/TakeSnapshotHandler.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotDescriptionUtils.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotFileCache.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotFileCacheWithDifferentWorkingDir.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/snapshot/TestSnapshotHFileCleaner.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/SnapshotTestingUtils.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/snapshot/TestSnapshotDescriptionUtils.java
Labels: backport

#1749 HBASE-24367 ScheduledChore log elapsed timespan in a human-friendly format
  hbase-common/src/main/java/org/apache/hadoop/hbase/ScheduledChore.java
Labels: enhancement

#1743 HBASE-24403 FsDelegationToken Should Cache Token After Acquired A New One
  hbase-server/src/main/java/org/apache/hadoop/hbase/security/token/FsDelegationToken.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/tool/BulkLoadHFilesTool.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/security/token/TestFsDelegationToken.java
Labels: enhancement

#1913 HBASE-24577 Doc WALSplitter classes
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedRecoveredHFilesOutputSink.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/RecoveredEditsOutputSink.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALSplitToHFile.java
Labels: enhancement

#1912 HBASE-24574 Procedure V2 - Distributed WAL Splitting => LOGGING
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitLogManager.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/SplitWALManager.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/AssignmentManager.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionRemoteProcedureBase.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/RegionTransitionProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/ServerCrashProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SplitWALProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/SplitWALRemoteProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/SplitWALCallable.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
Labels: enhancement

#1927 HBASE-24592 [branch-2.2] Upgrade junit to 4.13
  pom.xml
Labels: enhancement

#1925 HBASE-24591 get_table_rsgroup ignored the existence of rsgroup config…
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsAdmin1.java
Labels: bug

#1937 HBASE-24598 : Backport HBASE-24380 (Provide WAL splitting journal logging) (#1860)
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/LogRecoveredEditsOutputSink.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WALSplitter.java
Labels: backport

#1934 HBASE-24594 : Separate resource allocation for TestReplicationStatusSink
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStatus.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStatusSink.java
Labels: enhancement

#1928 HBASE-24593 [branch-2.2] Fix the maven compilation failure for nightl…
  hbase-client/src/test/java/org/apache/hadoop/hbase/ipc/TestNettyRpcConnection.java
Labels: bug

#1929 HBASE-24205 Create metric to know the number of reads that happens from memstore
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSource.java
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapper.java
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregate.java
  hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionSourceImpl.java
  hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableAggregateSourceImpl.java
  hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableSourceImpl.java
  hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperStub.java
  hbase-hadoop2-compat/src/test/java/org/apache/hadoop/hbase/regionserver/TestMetricsRegionSourceImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/KeyValueHeap.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsTableWrapperAggregateImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/Store.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreScanner.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionWrapperStub.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestStoreScanner.java
Labels: enhancement

#1782 HBASE-24431 RSGroupInfo add configuration map to store something extra
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AdminOverAsyncAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfo.java
  hbase-protocol-shaded/src/main/protobuf/server/master/Master.proto
  hbase-protocol-shaded/src/main/protobuf/server/rsgroup/RSGroup.proto
  hbase-protocol-shaded/src/main/protobuf/server/rsgroup/RSGroupAdmin.proto
  hbase-server/src/main/java/org/apache/hadoop/hbase/coprocessor/MasterObserver.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterCoprocessorHost.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/DisabledRSGroupInfoManager.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManager.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupInfoManagerImpl.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupConfig.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/VerifyingRSGroupAdmin.java
  hbase-shell/src/main/ruby/hbase/rsgroup_admin.rb
  hbase-shell/src/main/ruby/shell.rb
  hbase-shell/src/main/ruby/shell/commands/alter_rsgroup_config.rb
  hbase-shell/src/main/ruby/shell/commands/show_rsgroup_config.rb
  hbase-shell/src/test/ruby/shell/rsgroup_shell_test.rb
  hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
Labels: feature

#1730 HBASE-24289 Heterogeneous Storage for Date Tiered Compaction
  dev-support/design-docs/HBASE-24289-Heterogeneous Storage for Date Tiered Compaction.md
  hbase-common/src/main/java/org/apache/hadoop/hbase/HConstants.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/AbstractMultiFileWriter.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DateTieredMultiFileWriter.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/DateTieredStoreEngine.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HStore.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/StoreFileWriter.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/AbstractMultiOutputCompactor.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/CompactionConfiguration.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/Compactor.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/DateTieredCompactionPolicy.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/DateTieredCompactionRequest.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/compactions/DateTieredCompactor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/AbstractTestDateTieredCompactionPolicy.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestDateTieredCompactionPolicyHeterogeneousStorage.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestDateTieredCompactor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestStripeCompactionPolicy.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/compactions/TestStripeCompactor.java
Labels: feature
