Repository apache/hbase, pull requests merged in 2020-08, with the labels that each got.

#2197 HBASE-24807 Backport HBASE-20417 to branch-1
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSource.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/ReplicationSourceWALReaderThread.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestWALEntryStream.java
Labels: backport

#2199 HBASE-24819 Fix flaky test TestRaceBetweenSCPAndDTP and TestRaceBetwe…
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRaceBetweenSCPAndDTP.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRaceBetweenSCPAndTRSP.java
Labels: backport, enhancement

#2192 Backport "HBASE-24662 Update DumpClusterStatusAction to notice changes in region server count" to branch-1
  hbase-it/src/test/java/org/apache/hadoop/hbase/chaos/actions/DumpClusterStatusAction.java
Labels: backport

#762 HBASE-23157 WAL unflushed seqId tracking may wrong when Durability.AS…
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/ImmutableByteArray.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/AbstractFSWAL.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/SequenceIdAccounting.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/DisabledWALProvider.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/WAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestFSWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/AbstractTestWALReplay.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestSequenceIdAccounting.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestFSHLogProvider.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/wal/TestWALFactory.java
Labels: bug

#2224 HBASE-24838 The pre commit job fails to archive surefire reports
  dev-support/Jenkinsfile_GitHub
Labels: bug

#2213 Backport: HBASE-24824 Add more stats in PE for read replica (#2205)
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
Labels: backport

#2212 Backport: HBASE-24824 Add more stats in PE for read replica (#2205)
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/PerformanceEvaluation.java
Labels: backport

#2230 HBASE-22524 Refactor TestReplicationSyncUpTool
  hbase-endpoint/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSyncUpToolWithBulkLoadedData.java
  hbase-mapreduce/src/test/java/org/apache/hadoop/hbase/replication/TestVerifyReplication.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/replication/TestReplicationAdminWithClusters.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestBulkLoadReplication.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestNamespaceReplication.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationChangingPeerRegionservers.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationDisableInactivePeer.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationDroppedTables.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEmptyWALRecovery.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationEndpoint.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationKillMasterRS.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationKillMasterRSCompressed.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationKillMasterRSWithSeparateOldWALs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationKillRS.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationKillSlaveRS.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationKillSlaveRSWithSeparateOldWALs.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationMetricsforUI.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSmallTests.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationStatus.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSyncUpTool.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSyncUpToolBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/multiwal/TestReplicationEndpointWithMultipleAsyncWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/multiwal/TestReplicationEndpointWithMultipleWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/multiwal/TestReplicationKillMasterRSCompressedWithMultipleAsyncWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/multiwal/TestReplicationKillMasterRSCompressedWithMultipleWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/multiwal/TestReplicationSyncUpToolWithMultipleAsyncWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/multiwal/TestReplicationSyncUpToolWithMultipleWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestReplicator.java
Labels: backport

#2214 HBASE-24750 : All ExecutorService should use guava ThreadFactoryBuilder
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncConnectionImpl.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClusterStatusListener.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/ConnectionImplementation.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/HTable.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/AbstractRpcClient.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/ipc/NettyRpcConnection.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestAsyncProcess.java
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/util/Threads.java
  hbase-examples/src/main/java/org/apache/hadoop/hbase/client/example/AsyncClientExample.java
  hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/RemoteProcedureDispatcher.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/ClusterStatusPublisher.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/assignment/SplitTableRegionProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/mob/MobUtils.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/namequeues/NamedQueueRecorder.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MemStoreFlusher.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/wal/FSHLog.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/RegionReplicaReplicationEndpoint.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/snapshot/SnapshotManifest.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/tool/HFileContentValidator.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/HBaseFsck.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/ModifyRegionUtils.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/MultiHConnection.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/OutputSink.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/AcidGuaranteesTestTool.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableGetMultiThreaded.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestConnectionImplementation.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/coprocessor/TestOpenTableInCoprocessor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionStates.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/compactions/TestMobCompactor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/compactions/TestPartitionedMobCompactor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/procedure/SimpleRSProcedureManager.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionServerReportForDuty.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncFSWAL.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/wal/TestAsyncWALReplay.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestHBaseFsckMOB.java
  hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift/IncrementCoalescer.java
  hbase-zookeeper/src/main/java/org/apache/hadoop/hbase/zookeeper/ZKWatcher.java
Labels: backport

#2248 HBASE-24870 Ignore TestAsyncTableRSCrashPublish
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncTableRSCrashPublish.java
Labels: enhancement

#2273 Backport "HBASE-24627 Normalize one table at a time" to branch-2
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/Admin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/AsyncHBaseAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/HBaseAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/NormalizeTableFilterParams.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/RawAsyncHBaseAdmin.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/ProtobufUtil.java
  hbase-client/src/main/java/org/apache/hadoop/hbase/shaded/protobuf/RequestConverter.java
  hbase-protocol-shaded/src/main/protobuf/Master.proto
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/MasterRpcServices.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/normalizer/TestSimpleRegionNormalizerOnCluster.java
  hbase-shell/src/main/ruby/hbase/admin.rb
  hbase-shell/src/main/ruby/hbase_constants.rb
  hbase-shell/src/main/ruby/shell/commands/normalize.rb
  hbase-thrift/src/main/java/org/apache/hadoop/hbase/thrift2/client/ThriftAdmin.java
Labels: backport

#2305 HBASE-24946 Remove the metrics assert in TestClusterRestartFailover
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestClusterRestartFailover.java
Labels: enhancement

#2149 HBASE-24760 Add a config hbase.rsgroup.fallback.enable for RSGroup fallback feature
  hbase-server/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsFallback.java
Labels: feature

#2317 HBASE-24949 Optimize FSTableDescriptors.get to not always go to fs wh…
  hbase-server/src/main/java/org/apache/hadoop/hbase/TableDescriptors.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CloneSnapshotProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CreateTableProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/InitMetaProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/TruncateTableProcedure.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSTableDescriptors.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/MockMasterServices.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestReadAndWriteRegionInfoFile.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/util/TestFSTableDescriptors.java
Labels: enhancement

#2286 HBASE-24913 Refactor TestJMXConnectorServer
  hbase-server/src/test/java/org/apache/hadoop/hbase/TestJMXConnectorServer.java
Labels: enhancement

#2332 HBASE-24968 : Move META_COMPARATOR to subclass MetaCellComparator
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/CellComparatorImpl.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/KeyValue.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/MetaCellComparator.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/TestCellComparator.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/TestKeyValue.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/FixedFileTrailer.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileWriterImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedRecoveredHFilesOutputSink.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/MetaMockingUtil.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestFixedFileTrailer.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
Labels: backport

#2333 HBASE-24968 : Move META_COMPARATOR to subclass MetaCellComparator
  hbase-client/src/test/java/org/apache/hadoop/hbase/client/TestClientNoCluster.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/CellComparatorImpl.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/KeyValue.java
  hbase-common/src/main/java/org/apache/hadoop/hbase/MetaCellComparator.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/TestCellComparator.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/TestKeyValue.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/FixedFileTrailer.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/io/hfile/HFileWriterImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegion.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/wal/BoundedRecoveredHFilesOutputSink.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/MetaMockingUtil.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestFixedFileTrailer.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/io/hfile/TestHFile.java
Labels: backport
