Repository apache/hbase, pull requests merged in 2020-07, with the labels that each got.

#1963 HBASE-24624 Optimize table.jsp code
  hbase-server/src/main/resources/hbase-webapps/master/table.jsp
Labels: enhancement

#1900 HBASE-24546 CloneSnapshotProcedure unlimited retry
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/procedure/CloneSnapshotProcedure.java
Labels: bug

#2039 HBASE-22738 Fallback to default group to choose RS when there are no …
  hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupBasedLoadBalancer.java
  hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsBase.java
  hbase-rsgroup/src/test/java/org/apache/hadoop/hbase/rsgroup/TestRSGroupsFallback.java
Labels: backport

#2016 HBASE-24653 Show snapshot owner on Master WebUI
  hbase-server/src/main/jamon/org/apache/hadoop/hbase/tmpl/master/MasterStatusTmpl.jamon
  hbase-server/src/main/resources/hbase-webapps/master/snapshotsStats.jsp
Labels: enhancement

#2035 HBASE-24663 Add procedure process time statistics UI
  hbase-metrics/src/main/java/org/apache/hadoop/hbase/metrics/impl/HistogramImpl.java
  hbase-server/src/main/resources/hbase-webapps/master/procedures.jsp
Labels: enhancement

#1986 HBASE-24581 Skip compaction request/check for replica regions at the …
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/HRegionServer.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestRegionReplicaSplit.java
Labels: enhancement

#2173 HBASE-24788: Fix the connection leaks on getting hbase admin from unclosed connection
  hbase-mapreduce/src/main/java/org/apache/hadoop/hbase/mapreduce/TableOutputFormat.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/ServerRegionReplicaUtil.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestAsyncReplicationAdminApiWithClusters.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestClearRegionBlockCache.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestMasterReplication.java
Labels: backport

#2170 HBASE-24788: Fix the connection leaks on getting hbase admin from unc…
  hbase-server/src/main/java/org/apache/hadoop/hbase/mapreduce/TableOutputFormat.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/TestReplicationSmallTests.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/security/access/TestNamespaceCommands.java
Labels: backport
