Repository apache/hbase, pull requests merged in 2020-02, with the labels that each got.

#1111 HBASE-23777 Removed deprecated createTableDescriptor(String, int, int, int, KeepDeletedCells) from HBaseTestingUtility
  hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestKeepDeletes.java
Labels: enhancement

#1115 HBASE-23782 We still reference the hard coded meta descriptor in some…
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSTableDescriptors.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/TestHBaseMetaEdit.java
Labels: bug

#1107 HBASE-23772 Removed deprecated getTimeStampOfLastShippedOp from MetricsSource
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/MetricsSource.java
Labels: enhancement

#1142 HBASE-23809 The RSGroup shell test is missing
  hbase-rsgroup/src/main/java/org/apache/hadoop/hbase/rsgroup/RSGroupAdminServer.java
  hbase-shell/src/test/java/org/apache/hadoop/hbase/client/AbstractTestShell.java
  hbase-shell/src/test/java/org/apache/hadoop/hbase/client/TestRSGroupShell.java
Labels: bug

#1026 HBASE-23682 Fix NPE when disable DeadServerMetricRegionChore
  hbase-procedure/src/main/java/org/apache/hadoop/hbase/procedure2/ProcedureExecutor.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/assignment/TestDeadServerMetricRegionChore.java
Labels: bug

#1169 Backport HBASE-23808 to branch-2
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterShutdown.java
Labels: backport

#1170 Backport HBASE-23808 to branch-2.2
  hbase-server/src/main/java/org/apache/hadoop/hbase/master/HMaster.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/master/TestMasterShutdown.java
Labels: backport

#1168 HBASE-23837 Removed deprecated isLegalFamilyName(byte[]) from HColumnDescriptor
  hbase-client/src/main/java/org/apache/hadoop/hbase/HColumnDescriptor.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/util/FSUtils.java
Labels: enhancement

#1172 HBASE-23844 Removed deprecated Scan(byte[], Filter) from Scan
  hbase-client/src/main/java/org/apache/hadoop/hbase/client/Scan.java
Labels: enhancement

#1146 HBASE-23781 Removed deprecated createTableDescriptor(String) from HBaseTestingUtility
  hbase-it/src/test/java/org/apache/hadoop/hbase/IntegrationTestMobCompaction.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/HBaseTestingUtility.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestFromClientSide.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestReplicaWithCluster.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/client/TestReplicasClient.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobCompactionBase.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobFileCache.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobFileCleanerChore.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/mob/TestMobStoreCompaction.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestCompaction.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMajorCompaction.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestMinorCompaction.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestRegionReplicaFailover.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestScanner.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/TestSplitTransactionOnCluster.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestRegionReplicaReplicationEndpoint.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/replication/regionserver/TestRegionReplicaReplicationEndpointNoMaster.java
Labels: enhancement
