Repository apache/hbase, pull requests merged in 2020-09, with the labels that each got.

#2349 HBASE-24980 Fix dead links in HBase book
  src/main/asciidoc/_chapters/architecture.adoc
  src/main/asciidoc/_chapters/other_info.adoc
  src/site/asciidoc/metrics.adoc
Labels: enhancement

#2344 HBASE-24857:Fix several problems when starting webUI
  bin/hbase
  hbase-server/src/main/java/org/apache/hadoop/hbase/tool/CanaryTool.java
Labels: backport

#2367 HBASE-24994 Add hedgedReadOpsInCurThread metric
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
  hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
  src/main/asciidoc/_chapters/performance.adoc
Labels: backport

#2368 HBASE-24994 Add hedgedReadOpsInCurThread metric
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSource.java
  hbase-hadoop-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapper.java
  hbase-hadoop2-compat/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerSourceImpl.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperImpl.java
  hbase-server/src/test/java/org/apache/hadoop/hbase/regionserver/MetricsRegionServerWrapperStub.java
  src/main/asciidoc/_chapters/performance.adoc
Labels: backport

#2395 HBASE-25014 ScheduledChore is never triggered when initalDelay > 1.5*…
  hbase-common/src/main/java/org/apache/hadoop/hbase/ScheduledChore.java
  hbase-common/src/test/java/org/apache/hadoop/hbase/TestChoreService.java
Labels: bug

#2463 HBASE-25100 conf and conn are assigned twice in HBaseReplicationEndpo…
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/HBaseReplicationEndpoint.java
  hbase-server/src/main/java/org/apache/hadoop/hbase/replication/regionserver/HBaseInterClusterReplicationEndpoint.java
Labels: bug
